config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :albums do
    member do
      get :purge_img
    end
  end

  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
  after_save :confirmation_email
  belongs_to :user
  has_and_belongs_to_many :tags
  has_one_attached :cover_image
  has_many_attached :images
  validates :title,:description,presence:true
  def tagged=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(album_tags: name.strip).first_or_create!
    end
  end

  def tagged
    tags.map(&:album_tags).join(", ")
  end
  private
    def confirmation_email
      ApplicationMailer.welcome_email(user).deliver_now
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :albums
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!,except: [:show]
  before_action :requireUpdate, only: [:edit,:destroy,:update]
  def index
    if user_signed_in?
      @published_albums = current_user.albums.where(published: true)
      @unpublished_albums = current_user.albums.where(published: false)
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end
 
  def create 
    @album = current_user.albums.new(album_params)
    
    if @album.save
      redirect_to @album 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update!(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to root_path, status: :see_other
  end

  def purge_img
    album = Album.find(params[:album_id])
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to album
  end

  private
    def album_params
      params.require(:album).permit(:title,:description,:published,:tagged,:cover_image,images:[])
    end

    def requireUpdate
      album = Album.find(params[:id])
      if current_user.id != album.user_id
        redirect_to root_path
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Album.where(published:true).ransack(params[:q])
    @albums = @q.result
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_albums.html.erb
<div class="container album_cards p-5">
 <h1 class=" row justify-content-center mb-4"><%=heading%></h1>
   <div class="row g-3 justify-content-center">
      <%albums.each do |album|%>
         <div class="col-lg-3 col-md-6">
            <div class="card album_card" >         
               <%= image_tag  album.cover_image, class:"card-img-top card_img"%>
               <div class="card-body text-center">
                  <h5 class="card-title"><%=album.title%></h5>
                  <p class="text"><%=album.description%></p>
                  <p class="text"><b>Created by: </b><%=album.user.username%></p>
                  <p class="card-text"><b>Created at: </b><%=album.created_at.to_date%></p>
                  <p class="card-text"><b>Last updated: </b><%=time_ago_in_words(album.updated_at)%> ago</p>
                  <p class="card-text"><b>Tagged by:</b> <%=album.tagged%></p>
                <%=link_to "Go to Album",album,class:"btn btn-success"%>
               </div>
            </div>
         </div>
      <%end%>
   </div>
</div>

app/views/albums/_form.html.erb
<div class="container w-50 mx-auto px-auto ">

    <%= form_with model: album  do |form|%>
      <div class="mb-3">
        <%=form.label :title,class:"form-label"%><br>
        <%=form.text_field :title,class:"form-control"%>
        <%album.errors.full_messages_for(:title).each do |message|%>
          <div><%=message%></div>
        <%end%>
      </div>

      <div class="mb-3">
        <%=form.label :description,class:"form-label"%><br>
        <%=form.text_field :description,class:"form-control"%>
        <%album.errors.full_messages_for(:description).each do |message|%>
          <div><%=message%></div>
        <%end%>
      </div>

      <div class="mb-3">
        <%=form.label :cover_image,class:"form-label"%><br>
        <%=form.file_field :cover_image,class:"form-control"%>
      </div>

      <div class="mb-3">
        <%=form.label :images,"select Images",class:"form-label"%><br>
        <%=form.file_field :images,direct_upload: true,multiple: true, class:"form-control"%>
      </div>

      <div class="mb-3">
        <%=form.label :tagged,"Album Tags",class:"form-label"%><br>
        <%=form.text_field :tagged,class:"form-control"%>
      </div>

      <div class="mb-3">
        <%=form.check_box :published,checked:true,class:"form-check-input"%>
        <%=form.label :published,class:"form-check-label"%>
      </div>

      <div class="mb-3">
       <%=form.submit class:"btn btn-success"%>
      </div>
    <%end%>
</div>

app/views/albums/edit.html.erb
<h2 class="mb-3 text-center"> Edit Album</h2>
<%=render "form",album:@album%>

app/views/albums/index.html.erb
 <%=render "albums",albums:@published_albums, heading:"published albums"%><hr>
 <%=render "albums",albums:@unpublished_albums, heading:"unpublished albums"%> 

app/views/albums/new.html.erb
<h2 class="mb-3 text-center"> Add new Album</h2>
<%=render "form",album: @album%>

app/views/albums/show.html.erb
<h2 class="text-center mt-3"><%=@album.title%></h2>
<p class="text-center"><%=@album.description%></p>
<div class="container mb-3">
  <% if @album.images.attached?%>
     <div class="row mx-auto gy-4">
      <% @album.images.each do |img| %>
         <div class="col-lg-3  col-sm-6 justify-content-center position-relative">
            <%= image_tag img, style:"width:300px;height:300px;"%>
            <%if user_signed_in? && current_user.id == @album.user_id%>
               <%=link_to "X",purge_img_album_path(id: img.id, album_id: @album.id), class:"btn btn-danger rounded-circle position-absolute top-0 end-0"%>
            <%end%>
         </div>
      <%end%>
     </div>
   <%end%>
   <%if user_signed_in? && current_user.id==@album.user_id%>
      <div class="row d-flex justify-content-center my-4">
         <%= link_to "Edit Album",edit_album_path, class:"btn btn-warning col-md-6 w-25"%>
         <%=link_to "destroy",album_path(@album),data:{
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
         },class:"btn btn-danger ms-2 col-md-6 w-25"%>
      </div>
   <%end%>
</div>

app/views/home/index.html.erb
<%= search_form_for @q, class:"w-25 m-auto text-center",url: :root do |f| %>
<%= f.label :tags,"Search By Tags",class:"mb-2 fw-bold "%>
<%= f.search_field :tags_album_tags_cont, class: 'form-control mb-2 ' %>
<%= f.submit class: 'btn btn-primary d-inline' %>
<% end %>
<%=render "albums/albums",albums:@albums,heading:"All albums"%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href=<%=root_path%>>GalleryApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%=root_path%>>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=new_album_path%>>Create Album</a>
        </li>
        
        <%if user_signed_in?%>

          <li class="nav-item">
            <%=link_to "My albums",albums_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%=link_to current_user.email, root_path, class:"nav-link text-white "%>
          </li> 

          <li class="nav-item">
              <%=link_to "Logout",destroy_user_session_path,data:{
              turbo_method: :delete,
              turbo_confirm: "Are you sure want to logout?"
             },class:"nav-link"%>
          </li>
        <%else%>
            <li class="nav-item">
              <%=link_to "Login",user_session_path,class:"nav-link"%>
            </li>
        <%end%>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>GalleryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>